### ISSUE TITLE
Not working in php file

### ISSUE THREAD

**Issue by yura-brd** [anstarovoyt/intellij-extract-css#3]
Not working in php file

**Comment by anstarovoyt** [comment]
Hi! Could you please share a code sample? Or a sample project where you want to see this functionality

**Comment by yura-brd** [comment]
plugin does not work in PHP files. In the sense that if there is HTML in the file, then the plugin still does not work.

**Comment by a-zhary** [comment]
The same problem. Version PhpStorm 2022.1
For example:
![image](https://user-images.githubusercontent.com/16487977/165689552-12a5fc5f-112f-4eb7-9f14-8efb5ddc7a7b.png)

**Comment by anstarovoyt** [comment]
Hi! Thank you for the report. Fixed in 1.1.221
